[package]
name = "bgit"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
clap_complete = "4.5.14"
dialoguer = "0.11.0"
git2 = "0.19.0"
